# Generated by Django 5.0.4 on 2024-04-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_name_business_business_name_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
