# Generated by Django 5.0.4 on 2024-04-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_business_business_created_at_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounty',
            name='county',
        ),
        migrations.RemoveField(
            model_name='location',
            name='ward',
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_businesses', to='location.location'),
        ),
        migrations.RemoveField(
            model_name='ward',
            name='sub_county',
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
