# Generated by Django 5.0.4 on 2024-04-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_subcounty_county_remove_location_ward_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.AddField(
            model_name='business',
            name='building_name',
            field=models.CharField(default='Viewpark Towers', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='location.ward'),
        ),
    ]
